#include "dma.h"
#include "config.h"
#include "encoder.h"

void DmaCfg(void)
{
    /* DMA1 + AOS clock enable.
     *
     * IMPORTANT:
     * For this MA732 one-frame read, RX DMA is useful, but TX DMA is NOT used.
     * HC32 SPI TX-DMA request is generated by the SPTI pulse. If we only enable
     * TX DMA while the SPI transmit buffer is already empty, no new edge may be
     * generated, so DMA may never start. Therefore we enable RX DMA first and
     * manually write one 16-bit dummy/read command to SPI->DR to generate SCK.
     */
    FCG_Fcg0PeriphClockCmd(FCG0_PERIPH_DMA1, ENABLE);
    FCG_Fcg0PeriphClockCmd(FCG0_PERIPH_AOS, ENABLE);

    /* CH0: SPI1 receive buffer not empty -> memory. */
    AOS_SetTriggerEventSrc(AOS_DMA1_0, MA732_SPI_RX_DMA_EVENT);

    DMA_ClearTransCompleteStatus(CM_DMA1, DMA_INT_BTC_CH0);
    DMA_ClearTransCompleteStatus(CM_DMA1, DMA_INT_TRANS_ERR_CH0);
    DMA_ClearTransCompleteStatus(CM_DMA1, DMA_INT_TRANS_ERR_CH1);

    DMA_Cmd(CM_DMA1, ENABLE);
}

void DMA1_Error_Handler(void)
{
    DMA_ClearTransCompleteStatus(CM_DMA1, DMA_INT_TRANS_ERR_CH0);
    DMA_ClearTransCompleteStatus(CM_DMA1, DMA_INT_TRANS_ERR_CH1);
    MA732_DMA_ErrorCallback();
}

/* INT_SRC_DMA1_BTC0 Callback: SPI1 RX DMA complete. */
void DMA1_TC0_BTC0_Handler(void)
{
    DMA_ClearTransCompleteStatus(CM_DMA1, DMA_INT_BTC_CH0);
    MA732_DMA_RxDoneCallback();
}


